"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ActionSdkCommand;
(function (ActionSdkCommand) {
    ActionSdkCommand["CreateActionInstance"] = "CreateActionInstance";
    ActionSdkCommand["CreateActionInstanceWithRows"] = "CreateActionInstanceWithRows";
    ActionSdkCommand["GetActionInstance"] = "GetActionInstance";
    ActionSdkCommand["UpdateActionInstance"] = "UpdateActionInstance";
    ActionSdkCommand["DeleteActionInstance"] = "DeleteActionInstance";
    ActionSdkCommand["SendActionInstanceReminder"] = "SendActionInstanceReminder";
    ActionSdkCommand["CreateOrUpdateActionInstanceRows"] = "CreateOrUpdateActionInstanceRows";
    ActionSdkCommand["GetActionInstanceRow"] = "GetActionInstanceRow";
    ActionSdkCommand["GetActionInstanceRows"] = "GetActionInstanceRows";
    ActionSdkCommand["DeleteActionInstanceRow"] = "DeleteActionInstanceRow";
    ActionSdkCommand["GetActionInstanceSummary"] = "GetActionInstanceSummary";
    ActionSdkCommand["DownloadActionInstanceResult"] = "DownloadActionInstanceResult";
    ActionSdkCommand["GetActionInstanceNonResponoders"] = "GetActionInstanceNonResponoders";
    ActionSdkCommand["GetConversationMembers"] = "GetConversationMembers";
    ActionSdkCommand["GetConversationMembersCount"] = "GetConversationMembersCount";
    ActionSdkCommand["GetUserProfiles"] = "GetUserProfiles";
    ActionSdkCommand["GetUserProfilePhotos"] = "GetUserProfilePhotos";
    ActionSdkCommand["SetNavBarMenuItems"] = "SetNavBarMenuItems";
    ActionSdkCommand["UploadMedia"] = "UploadMedia";
    ActionSdkCommand["DismissScreen"] = "DismissScreen";
    ActionSdkCommand["GetCurrentContext"] = "GetCurrentContext";
    ActionSdkCommand["LogTelemetry"] = "LogTelemetry";
    ActionSdkCommand["GetLocalizedActionStrings"] = "GetLocalizedActionStrings";
    ActionSdkCommand["ShowDiagnosticView"] = "ShowDiagnosticView";
    ActionSdkCommand["HideLoadingIndicator"] = "HideLoadingIndicator";
    ActionSdkCommand["ActionViewDidLoad"] = "ActionViewDidLoad";
    ActionSdkCommand["RegisterBackButtonHandler"] = "RegisterBackButtonHandler";
    ActionSdkCommand["GetTemplateActions"] = "GetTemplateActions";
    ActionSdkCommand["GetActionInstances"] = "GetActionInstances";
    ActionSdkCommand["SaveActionInstanceDraft"] = "SaveActionInstanceDraft";
    ActionSdkCommand["UpdateActionInstanceDraft"] = "UpdateActionInstanceDraft";
    ActionSdkCommand["GetDraftActionInstances"] = "GetDraftActionInstances";
    ActionSdkCommand["PromoteDraftToAction"] = "PromoteDraftToAction";
    ActionSdkCommand["CreateActionInstanceNoBot"] = "CreateActionInstanceNoBot";
    ActionSdkCommand["GetJoinedTeams"] = "GetJoinedTeams";
    ActionSdkCommand["GetListOfChannelsForGroups"] = "GetListOfChannelsForGroups";
})(ActionSdkCommand = exports.ActionSdkCommand || (exports.ActionSdkCommand = {}));
